### ISSUE TITLE
cannot use xlsx function

### ISSUE THREAD

**Issue by offeex** [LuisEnMarroquin/json-as-xlsx#87]
```ts
import {IJsonSheet, xlsx} from "json-as-xlsx"

const data: IJsonSheet[] = [{
  sheet: 'BazaDizainerov-Kyiv-15-50',
  columns: [
    { label: 'name', value: 'name' },
    { label: 'email', value: 'email' },
    { label: 'phone', value: 'phone' },
    { label: 'city', value: 'city' },
    { label: 'company_type', value: 'company_type' },
    { label: 'experience', value: 'experience' },
    { label: 'portfolio', value: 'portfolio' },
    { label: 'price', value: 'price' },
    { label: 'opys_robit', value: 'opys_robit' }
  ],
  content: products
}]

fs.writeFileSync('data.xlsx', xlsx(data))
```

Here's what i get:
```
TypeError: xlsx is not a function
    at file:///home/offeex/Code/Standalone/designer-parser/index.ts:54:31
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)
```

**Comment by flamngoapp** [comment]
Hey, I am getting the same error. When I import all from `'json-as-xlsx'` I can actually see that the exported `xlsx` property is nil.

**Comment by LuisEnMarroquin** [comment]
Hi, not sure why this is happenning, last build was a day ago and this issue was reported 3 days ago

<img width="1231" alt="image" src="https://github.com/LuisEnMarroquin/json-as-xlsx/assets/35376824/447d8ce9-e821-4116-831f-08cf9696e24b">

https://www.npmjs.com/package/json-as-xlsx?activeTab=versions

I also tried with a demo project

* package.json

```json
{
  "name": "json-text",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "npx ts-node index.ts"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "json-as-xlsx": "^2.5.5"
  },
  "devDependencies": {
    "@types/node": "^20.8.7"
  }
}
```

* tsconfig.json

```json
{
  "compilerOptions": {
    "types": ["node"],
    "moduleResolution": "node",
    "target": "es2018"
  }
}
```

* index.ts

```ts
import xlsx, { IJsonSheet } from "json-as-xlsx";
import { writeFileSync } from "fs";

const products = [
  {
    name: "John Doe",
    email: "john.doe@example.com",
    phone: "+1234567890",
    city: "New York",
    company_type: "Software Development",
    experience: "5 years",
    portfolio: "www.johndoeportfolio.com",
    price: "$5000",
    opys_robit: "Web development, mobile applications, UI/UX design",
  },
  {
    name: "Jane Smith",
    email: "jane.smith@example.com",
    phone: "+0987654321",
    city: "Los Angeles",
    company_type: "Graphic Design",
    experience: "3 years",
    portfolio: "www.janesmithdesigns.com",
    price: "$4000",
    opys_robit: "Logo design, branding, print design",
  },
];

const data: IJsonSheet[] = [
  {
    sheet: "BazaDizainerov-Kyiv-15-50",
    columns: [
      { label: "name", value: "name" },
      { label: "email", value: "email" },
      { label: "phone", value: "phone" },
      { label: "city", value: "city" },
      { label: "company_type", value: "company_type" },
      { label: "experience", value: "experience" },
      { label: "portfolio", value: "portfolio" },
      { label: "price", value: "price" },
      { label: "opys_robit", value: "opys_robit" },
    ],
    content: products,
  },
];

writeFileSync("data.xlsx", xlsx(data));
```

this is also the error than I am getting

```shell
json-text ☭ nr start

> json-text@1.0.0 start
> npx ts-node index.ts

/Users/XXX/Projects/json-text/index.ts:47
writeFileSync("data.xlsx", xlsx(data));
                               ^
TypeError: (0 , json_as_xlsx_1.default) is not a function
    at Object.<anonymous> (/Users/XXX/Projects/json-text/index.ts:47:32)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module.m._compile (/Users/XXX/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/XXX/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at phase4 (/Users/XXX/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/bin.ts:649:14)
    at bootstrap (/Users/XXX/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/bin.ts:95:10)
json-text ☭ 
```

**Comment by dev-talha-anwar** [comment]
i was getting same error solved it by using require instead of import like this

// eslint-disable-next-line @typescript-eslint/no-var-requires
const xlsx = require('json-as-xlsx');

**Comment by LuisEnMarroquin** [comment]
@debuxxed @flamngoapp @dev-talha-anwar thanks for reporting this and for sharing the workaround.

I tracked this down to the CommonJS export shape. The package kept `require("json-as-xlsx")` working by assigning `module.exports = xlsx`, but that assignment dropped the runtime `xlsx` and `default` bindings that named/default import styles expect. Support for the named `xlsx` export had been added recently at the type level, but the runtime export surface was missing the matching binding.

This is fixed in commit 9fc97ea and released in `json-as-xlsx@2.6.3`, which is now available on npm. I also added a regression test and verified these import styles all resolve to the function:

```ts
import { xlsx } from "json-as-xlsx"
import xlsx from "json-as-xlsx"
const xlsx = require("json-as-xlsx")
```

I'll keep this issue closed since it is resolved now, but please feel free to reopen it or open a new issue if you still run into any problem after upgrading to 2.6.3. Thanks again!
